(deftheme cs-misterioso
  "Created 2016-09-26.")

(custom-theme-set-variables
 'cs-misterioso
 '(ansi-color-names-vector ["#2d3743" "#ff4242" "#74af68" "#dbdb95" "#34cae2" "#008b8b" "#00ede1" "#e1e1e0"]))

(custom-theme-set-faces
 'cs-misterioso
 '(cursor ((((class color) (min-colors 89)) (:background "#415160"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#2e3748"))))
 '(highlight ((((class color) (min-colors 89)) (:background "#338f86" :foreground "#e1e1e0"))))
 '(region ((((class color) (min-colors 89)) (:background "#2d4948" :foreground "#e1e1e0"))))
 '(isearch ((((class color) (min-colors 89)) (:background "#fcffad" :foreground "#000000"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#338f86"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#ff4242"))))
 '(mode-line ((((class color) (min-colors 89)) (:background "#212931" :foreground "#eeeeec"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:background "#878787" :foreground "#eeeeec"))))
 '(header-line ((((class color) (min-colors 89)) (:background "#e5e5e5" :foreground "#333333"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#729fcf" :weight bold))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#23d7d7"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#74af68"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#008b8b"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#00ede1" :weight bold))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#ffad29" :weight bold))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#e67128"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#34cae2"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#dbdb95"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#ff4242" :weight bold))))
 '(button ((((class color) (min-colors 89)) (:underline t))))
 '(link ((((class color) (min-colors 89)) (:foreground "#59e9ff" :underline t))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#ed74cd" :underline t))))
 '(default ((((class color) (min-colors 4096)) (:background "#0e1115" :foreground "#e1e1e0")) (((class color) (min-colors 89)) (:background "#3a3a3a" :foreground "#e1e1e0"))))
 '(org-agenda-calendar-event ((t (:inherit (default)))))
 '(org-agenda-clocking ((t (:inherit (secondary-selection)))))
 '(org-agenda-current-time ((t (:inherit (org-time-grid)))))
 '(org-agenda-date-today ((t (:weight bold :slant italic :inherit (org-agenda-date)))))
 '(org-agenda-diary ((t (:inherit (default)))))
 '(org-agenda-done ((((class color) (min-colors 16) (background light)) (:foreground "ForestGreen")) (((class color) (min-colors 16) (background dark)) (:foreground "PaleGreen")) (((class color) (min-colors 8)) (:foreground "green")) (t (:bold nil))))
 '(org-agenda-filter-regexp ((t (:inherit (mode-line)))))
 '(org-agenda-restriction-lock ((((class color) (min-colors 88) (background light)) (:background "#eeeeee")) (((class color) (min-colors 88) (background dark)) (:background "#1C1C1C")) (((class color) (min-colors 16) (background light)) (:background "#eeeeee")) (((class color) (min-colors 16) (background dark)) (:background "#1C1C1C")) (((class color) (min-colors 8)) (:foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(org-archived ((t (:inherit (shadow)))))
 '(org-block-begin-line ((t (:inherit (org-meta-line)))))
 '(org-agenda-calendar-sexp ((t (:inherit (default)))))
 '(org-agenda-column-dateline ((t (:inherit (org-column)))))
 '(org-agenda-date ((t (:inherit (org-agenda-structure)))))
 '(org-agenda-date-weekend ((t (:weight bold :inherit (org-agenda-date)))))
 '(org-agenda-filter-category ((t (:inherit (mode-line)))))
 '(org-agenda-filter-tags ((t (:inherit (mode-line)))))
 '(org-agenda-structure ((((class color) (min-colors 88) (background light)) (:foreground "Blue1")) (((class color) (min-colors 88) (background dark)) (:foreground "LightSkyBlue")) (((class color) (min-colors 16) (background light)) (:foreground "Blue")) (((class color) (min-colors 16) (background dark)) (:foreground "LightSkyBlue")) (((class color) (min-colors 8)) (:bold t :foreground "blue")) (t (:bold t))))
 '(org-block ((t (:inherit (shadow)))))
 '(org-block-end-line ((t (:inherit (org-block-begin-line)))))
 '(org-checkbox ((t (:inherit (bold)))))
 '(org-todo ((t (:foreground "#ff4242" :weight bold))))
 '(org-hide ((t (:foreground "#0e1115"))))
 '(org-done ((t (:foreground "#008b8b" :weight bold))))
 '(org-checkbox-statistics-todo ((t (:inherit (org-todo)))))
 '(org-code ((t (:inherit (shadow)))))
 '(org-column-title ((((class color) (min-colors 16) (background light)) (:weight bold :underline (:color foreground-color :style line) :background "grey90")) (((class color) (min-colors 16) (background dark)) (:weight bold :underline (:color foreground-color :style line) :background "grey30")) (((class color) (min-colors 8)) (:weight bold :underline (:color foreground-color :style line) :foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(org-date-selected ((((class color) (min-colors 16) (background light)) (:inverse-video t :foreground "Red1")) (((class color) (min-colors 16) (background dark)) (:inverse-video t :foreground "Pink")) (((class color) (min-colors 8) (background light)) (:inverse-video t :foreground "red")) (((class color) (min-colors 8) (background dark)) (:inverse-video t :foreground "red")) (t (:inverse-video t))))
 '(org-document-info ((((class color) (background light)) (:foreground "midnight blue")) (((class color) (background dark)) (:foreground "pale turquoise")) (t nil)))
 '(org-document-title ((((class color) (background light)) (:weight bold :foreground "midnight blue")) (((class color) (background dark)) (:weight bold :foreground "pale turquoise")) (t (:weight bold))))
 '(org-drawer ((((class color) (min-colors 88) (background light)) (:foreground "Blue1")) (((class color) (min-colors 88) (background dark)) (:foreground "LightSkyBlue")) (((class color) (min-colors 16) (background light)) (:foreground "Blue")) (((class color) (min-colors 16) (background dark)) (:foreground "LightSkyBlue")) (((class color) (min-colors 8)) (:bold t :foreground "blue")) (t (:bold t))))
 '(org-footnote ((((class color) (background light)) (:underline (:color foreground-color :style line) :foreground "Purple")) (((class color) (background dark)) (:underline (:color foreground-color :style line) :foreground "Cyan")) (t (:underline (:color foreground-color :style line)))))
 '(org-headline-done ((((class color) (min-colors 16) (background light)) (:foreground "RosyBrown")) (((class color) (min-colors 16) (background dark)) (:foreground "LightSalmon")) (((class color) (min-colors 8) (background light)) (:bold nil))))
 '(org-indent ((t (:inherit (org-hide)))))
 '(org-level-1 ((t (:inherit (outline-1)))))
 '(org-level-3 ((t (:inherit (outline-3)))))
 '(org-level-5 ((t (:inherit (outline-5)))))
 '(org-level-7 ((t (:inherit (outline-7)))))
 '(org-link ((t (:inherit (link)))))
 '(org-macro ((t (:inherit (org-latex-and-related)))))
 '(org-mode-line-clock ((t (:inherit (mode-line)))))
 '(org-priority ((t (:inherit (font-lock-keyword-face)))))
 '(org-quote ((t (:inherit (org-block)))))
 '(org-scheduled-previously ((((class color) (min-colors 88) (background light)) (:foreground "Firebrick")) (((class color) (min-colors 88) (background dark)) (:foreground "chocolate1")) (((class color) (min-colors 8) (background light)) (:foreground "red")) (((class color) (min-colors 8) (background dark)) (:bold t :foreground "red")) (t (:bold t))))
 '(org-sexp-date ((((class color) (background light)) (:foreground "Purple")) (((class color) (background dark)) (:foreground "Cyan")) (t (:underline (:color foreground-color :style line)))))
 '(org-table ((((class color) (min-colors 88) (background light)) (:foreground "Blue1")) (((class color) (min-colors 88) (background dark)) (:foreground "LightSkyBlue")) (((class color) (min-colors 16) (background light)) (:foreground "Blue")) (((class color) (min-colors 16) (background dark)) (:foreground "LightSkyBlue")) (((class color) (min-colors 8) (background light)) (:foreground "blue")) (((class color) (min-colors 8) (background dark)) nil)))
 '(org-tag-group ((t (:inherit (org-tag)))))
 '(org-time-grid ((((class color) (min-colors 16) (background light)) (:foreground "DarkGoldenrod")) (((class color) (min-colors 16) (background dark)) (:foreground "LightGoldenrod")) (((class color) (min-colors 8)) (:weight light :foreground "yellow"))))
 '(org-upcoming-deadline ((((class color) (min-colors 88) (background light)) (:foreground "Firebrick")) (((class color) (min-colors 88) (background dark)) (:foreground "chocolate1")) (((class color) (min-colors 8) (background light)) (:foreground "red")) (((class color) (min-colors 8) (background dark)) (:bold t :foreground "red")) (t (:bold t))))
 '(org-verse ((t (:inherit (org-block)))))
 '(org-checkbox-statistics-done ((t (:inherit (org-done)))))
 '(org-clock-overlay ((((class color) (min-colors 88) (background light)) (:foreground "black" :background "LightGray")) (((class color) (min-colors 88) (background dark)) (:foreground "white" :background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:foreground "black" :background "gray")) (((class color) (min-colors 16) (background dark)) (:foreground "white" :background "SkyBlue4")) (((class color) (min-colors 8)) (:foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(org-column ((((class color) (min-colors 16) (background light)) (:underline nil :strike-through nil :slant normal :weight normal :background "grey90")) (((class color) (min-colors 16) (background dark)) (:underline nil :strike-through nil :slant normal :weight normal :background "grey30")) (((class color) (min-colors 8)) (:underline nil :strike-through nil :slant normal :weight normal :foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(org-date ((((class color) (background light)) (:underline (:color foreground-color :style line) :foreground "Purple")) (((class color) (background dark)) (:underline (:color foreground-color :style line) :foreground "Cyan")) (t (:underline (:color foreground-color :style line)))))
 '(org-default ((t (:inherit (default)))))
 '(org-document-info-keyword ((t (:inherit (shadow)))))
 '(org-ellipsis ((((class color) (background light)) (:underline (:color foreground-color :style line) :foreground "DarkGoldenrod")) (((class color) (background dark)) (:underline (:color foreground-color :style line) :foreground "LightGoldenrod")) (t (:strike-through t))))
 '(org-formula ((((class color) (min-colors 88) (background light)) (:foreground "Firebrick")) (((class color) (min-colors 88) (background dark)) (:foreground "chocolate1")) (((class color) (min-colors 8) (background light)) (:foreground "red")) (((class color) (min-colors 8) (background dark)) (:foreground "red")) (t (:italic t :bold t))))
 '(org-latex-and-related ((((class grayscale) (background light)) (:inherit (underline) :foreground "DimGray")) (((class grayscale) (background dark)) (:inherit (underline) :foreground "LightGray")) (((class color) (background light)) (:foreground "SaddleBrown")) (((class color) (background dark)) (:foreground "burlywood")) (t (:inherit (underline)))))
 '(org-level-2 ((t (:inherit (outline-2)))))
 '(org-level-4 ((t (:inherit (outline-4)))))
 '(org-level-6 ((t (:inherit (outline-6)))))
 '(org-level-8 ((t (:inherit (outline-8)))))
 '(org-list-dt ((t (:bold t))))
 '(org-meta-line ((t (:inherit (font-lock-comment-face)))))
 '(org-mode-line-clock-overrun ((t (:background "red" :inherit (mode-line)))))
 '(org-property-value ((t nil)))
 '(org-scheduled ((((class color) (min-colors 88) (background light)) (:foreground "DarkGreen")) (((class color) (min-colors 88) (background dark)) (:foreground "PaleGreen")) (((class color) (min-colors 8)) (:foreground "green")) (t (:italic t :bold t))))
 '(org-scheduled-today ((((class color) (min-colors 88) (background light)) (:foreground "DarkGreen")) (((class color) (min-colors 88) (background dark)) (:foreground "PaleGreen")) (((class color) (min-colors 8)) (:foreground "green")) (t (:italic t :bold t))))
 '(org-special-keyword ((t (:inherit (font-lock-keyword-face)))))
 '(org-tag ((t (:bold t))))
 '(org-target ((((class color) (background light)) (:underline (:color foreground-color :style line))) (((class color) (background dark)) (:underline (:color foreground-color :style line))) (t (:underline (:color foreground-color :style line)))))
 '(org-verbatim ((t (:inherit (shadow)))))
 '(org-warning ((t (:inherit (font-lock-warning-face))))))

(provide-theme 'cs-misterioso)
